In [1]:
import numpy as np

## 数学定义

$$
X=(X_1, \cdots, X_K)\sim \operatorname{Dir}(\boldsymbol\alpha)
$$
- $\boldsymbol \alpha \in \mathbb R^K$
- 如果令 $\alpha_0=\sum_{i=1}^K\alpha_i$
    - $E[X_i]=\frac{\alpha_i}{\alpha_0}$

In [13]:
s = np.random.dirichlet((10, 5, 3), 20)
s.shape

(20, 3)

In [15]:
np.mean(s, axis=0)

array([0.55879715, 0.27953906, 0.16166379])

In [16]:
np.asarray([10, 5, 3])/18

array([0.55555556, 0.27777778, 0.16666667])

概率密度：

$$
f \left(x_1,\ldots, x_{K}; \alpha_1,\ldots, \alpha_K \right) = \frac{1}{\mathrm{B}(\boldsymbol\alpha)}\prod_{i=1}^K x_i^{\alpha_i - 1}
$$

- 要求
    - $\sum_{i=1}^Kx_i=1$

In [17]:
s.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])