- 相同 shape 的 vector 的 add 运算可以通过 concat 之后，基于一定的矩阵运算转化为 add
    - 比如 Transformer 中 multi-head self attention 的多个头输出之后的 concat or add

In [1]:
import torch
torch.manual_seed(42)

In [2]:
H, d = 3, 4

In [3]:
h1 = torch.randn(d)
h2 = torch.randn(d)
h3 = torch.randn(d)

In [4]:
h1 + h2 + h3

tensor([-0.3245,  0.2098,  2.9776,  0.4017])

In [5]:
h_concat = torch.concat([h1, h2, h3], dim=-1)
h_concat

tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,
         0.4617,  0.2674,  0.5349,  0.8094])

In [9]:
# (nh*dh, dh)
# (dh, dh) 的 identity matrix 纵向拼接 nh 个
W = torch.concat([torch.eye(d) for _ in range(H)], dim=0)
W

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [8]:
h_concat @ W

tensor([-0.3245,  0.2098,  2.9776,  0.4017])