## `np.kron`

- `\otimes`
$$
\mathbf{A}\otimes\mathbf{B} = \begin{bmatrix}
  a_{11} \mathbf{B} & \cdots & a_{1n}\mathbf{B} \\
             \vdots & \ddots &           \vdots \\
  a_{m1} \mathbf{B} & \cdots & a_{mn} \mathbf{B}
\end{bmatrix}
$$

- $\mathbf{A}\otimes\mathbf{B} \neq \mathbf{B}\otimes\mathbf{A}$

- Parameters: a, b: array_like
- Returns: out: ndarray
    - `a.shape = (r0,r1,..,rN)` and `b.shape = (s0,s1,...,sN)`
    - `out.shape = (r0*s0, r1*s1, ..., rN*SN)`
    - 因此要求 `len(a.shape) == len(b.shape)`

In [1]:
import numpy as np

### case 1

In [3]:
# a.shape = (3, ), b.shape = (2, )
np.kron([1, 10, 100], [5, 6])

array([  5,   6,  50,  60, 500, 600])

In [4]:
np.kron([5, 6], [1, 10, 100])

array([  5,  50, 500,   6,  60, 600])

### case 2

In [5]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [7]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# (2, 2)*(3, 3) ==> (6, 6)
np.kron(np.eye(2), 2*np.ones((3, 3)))

array([[2., 2., 2., 0., 0., 0.],
       [2., 2., 2., 0., 0., 0.],
       [2., 2., 2., 0., 0., 0.],
       [0., 0., 0., 2., 2., 2.],
       [0., 0., 0., 2., 2., 2.],
       [0., 0., 0., 2., 2., 2.]])