In [7]:
import numpy as np
from scipy import linalg

## $Ax=b$

$$
x=A^{-1}b
$$

- $A$ 需要可逆，$A$ 的行列式不能为0

In [2]:
A = np.array(
    [
        [1, 9, 2, 1, 1],
        [10, 1, 2, 1, 1],
        [1, 0, 5, 1, 1],
        [2, 1, 1, 2, 9],
        [2, 1, 2, 13, 2],
    ]
)

In [3]:
b = np.array([170, 180, 140, 180, 350]).reshape((-1, 1))

In [4]:
x = linalg.inv(A).dot(b)
x

array([[10.],
       [10.],
       [20.],
       [20.],
       [10.]])

In [6]:
linalg.solve(A, b)

array([[10.],
       [10.],
       [20.],
       [20.],
       [10.]])

## Moore-Penrose inverse

- 又叫伪逆（Pseudo inverse）、广义逆

## Wikipedia examples

- 取决于如何建模

### fitting a line

In [11]:
A = np.asarray([[1, 1], 
                [1, 2], 
                [1, 3], 
                [1, 4]])
y = np.asarray([6, 5, 7, 10]).reshape(-1, 1)

In [12]:
beta = np.linalg.inv(A.T.dot(A)).dot(A.T).dot(y)
beta

array([[3.5],
       [1.4]])

In [14]:
beta = np.linalg.pinv(A).dot(y)
beta

array([[3.5],
       [1.4]])

### fitting a parabola

In [19]:
A = np.asarray([[1], 
                [4], 
                [9], 
                [16]])
y = np.asarray([6, 5, 7, 10]).reshape(-1, 1)

In [20]:
beta = np.linalg.inv(A.T.dot(A)).dot(A.T).dot(y)
beta

array([[0.70338983]])

In [21]:
np.linalg.pinv(A).dot(y)

array([[0.70338983]])