In [1]:
import numpy as np

In [10]:
np.random.seed(42)

## 右乘以一个对角矩阵

$$
A_{mn}B_{nn}=\begin{bmatrix}
B_{11}A_1, \cdots,B_{ii}A_i,\cdots
\end{bmatrix}
$$

In [11]:
A = np.random.randint(0, 5, (2, 3))
A

array([[3, 4, 2],
       [4, 4, 1]])

In [12]:
B = np.diag([1, 2, 3])
B

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
A.dot(B)

array([[3, 8, 6],
       [4, 8, 3]])