> 从分块矩阵的角度，重新理解矩阵矢量乘法，矩阵乘法；
> - matrix vector multiplication
    - 矩阵右乘以 onehot vector 是一种特殊的矩阵矢量乘法，用于选择列；
    - 第$i$个entry为1，就是选择矩阵的第 $i$ 列；
> - matrix matrix multiplication
    - 矩阵右乘以对角矩阵是一种特殊的矩阵矩阵乘法（mm），是对原始矩阵各个列的伸缩；

In [2]:
import numpy as np

In [3]:
np.random.seed(42)

## 矩阵矢量乘法

In [4]:
A = np.random.randint(0, 5, (4, 3))
A

array([[3, 4, 2],
       [4, 4, 1],
       [2, 2, 2],
       [4, 3, 2]])

In [15]:
B = np.ones(3)[:, np.newaxis]
B

array([[1.],
       [1.],
       [1.]])

### 列的线性组合

> matrix-vector multiplication：column linear combination

In [16]:
# 列的线性组合
A.dot(B)

array([[8.],
       [8.],
       [4.],
       [7.]])

### 列选择

In [5]:
B = np.zeros(3)[:, np.newaxis]
# one shot
B[0] = 1
B

array([[1.],
       [0.],
       [0.]])

In [22]:
A

array([[4, 1, 3],
       [1, 3, 4],
       [0, 3, 1],
       [4, 3, 0]])

In [18]:
A.dot(B)

array([[4.],
       [1.],
       [0.],
       [4.]])

In [19]:
B = np.zeros(3)[:, np.newaxis]
B[0] = 2
B

array([[2.],
       [0.],
       [0.]])

In [23]:
A

array([[4, 1, 3],
       [1, 3, 4],
       [0, 3, 1],
       [4, 3, 0]])

In [20]:
A.dot(B)

array([[8.],
       [2.],
       [0.],
       [8.]])

In [25]:
B = np.zeros(3)[:, np.newaxis]
B[1] = 2
B

array([[0.],
       [2.],
       [0.]])

In [24]:
A

array([[4, 1, 3],
       [1, 3, 4],
       [0, 3, 1],
       [4, 3, 0]])

In [26]:
A.dot(B)

array([[2.],
       [6.],
       [6.],
       [6.]])

## 右乘以一个对角矩阵

$$
A_{mn}B_{nn}=\begin{bmatrix}
B_{11}A_1, \cdots,B_{ii}A_i,\cdots
\end{bmatrix}
$$

In [6]:
A = np.random.randint(0, 5, (2, 3))
A

array([[4, 1, 3],
       [1, 3, 4]])

In [7]:
B = np.diag([1, 2, 3])
B

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [8]:
A.dot(B)

array([[ 4,  2,  9],
       [ 1,  6, 12]])