In [1]:
import numpy as np

In [2]:
np.random.seed(42)

## 矩阵矢量乘法

In [5]:
A = np.random.randint(0, 5, (4, 3))
A

array([[4, 1, 3],
       [1, 3, 4],
       [0, 3, 1],
       [4, 3, 0]])

In [15]:
B = np.ones(3)[:, np.newaxis]
B

array([[1.],
       [1.],
       [1.]])

### 列的线性组合

In [16]:
# 列的线性组合
A.dot(B)

array([[8.],
       [8.],
       [4.],
       [7.]])

### 列选择

In [17]:
B = np.zeros(3)[:, np.newaxis]
B[0] = 1
B

array([[1.],
       [0.],
       [0.]])

In [22]:
A

array([[4, 1, 3],
       [1, 3, 4],
       [0, 3, 1],
       [4, 3, 0]])

In [18]:
A.dot(B)

array([[4.],
       [1.],
       [0.],
       [4.]])

In [19]:
B = np.zeros(3)[:, np.newaxis]
B[0] = 2
B

array([[2.],
       [0.],
       [0.]])

In [23]:
A

array([[4, 1, 3],
       [1, 3, 4],
       [0, 3, 1],
       [4, 3, 0]])

In [20]:
A.dot(B)

array([[8.],
       [2.],
       [0.],
       [8.]])

In [25]:
B = np.zeros(3)[:, np.newaxis]
B[1] = 2
B

array([[0.],
       [2.],
       [0.]])

In [24]:
A

array([[4, 1, 3],
       [1, 3, 4],
       [0, 3, 1],
       [4, 3, 0]])

In [26]:
A.dot(B)

array([[2.],
       [6.],
       [6.],
       [6.]])

## 右乘以一个对角矩阵

$$
A_{mn}B_{nn}=\begin{bmatrix}
B_{11}A_1, \cdots,B_{ii}A_i,\cdots
\end{bmatrix}
$$

In [4]:
A = np.random.randint(0, 5, (2, 3))
A

array([[2, 2, 2],
       [4, 3, 2]])

In [12]:
B = np.diag([1, 2, 3])
B

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
A.dot(B)

array([[3, 8, 6],
       [4, 8, 3]])