In [1]:
import numpy as np

## 正定矩阵（positive definite）

- A matrix is positive definite if it’s symmetric and all its **pivots** are positive.
    - 正定矩阵首先是对称的；（方阵）
    - pivots：一般翻译为主元；
- One way to tell if a matrix is positive definite is to calculate all the eigenvalues and just check to see if they’re all positive.

$$
x^TAx\gt 0, \quad \forall x\in\mathcal R^n \textbackslash \{0\}
$$

In [2]:
A = np.array([[2, 1], [1, 2]])
A

array([[2, 1],
       [1, 2]])

### 特征值检测

In [7]:
np.allclose(A, A.T)

True

In [5]:
eigvals = np.linalg.eigvals(A)
eigvals

array([3., 1.])

In [6]:
np.all(eigvals > 0)

True

### Cholesky 分解

- 一个矩阵能够 Cholesky 分解的前提必须是正定矩阵，
    - 也即对于一个非正定矩阵进行 Cholesky 分解，会抛错

In [8]:
np.linalg.cholesky(A)

array([[1.41421356, 0.        ],
       [0.70710678, 1.22474487]])

In [9]:
def is_pos_definite(A):
    if not np.allclose(A, A.T):
        return False
    try:
        np.linalg.cholesky(A)
        return True
    except np.linalg.LinAlgError:
        return False

In [10]:
A_prime = np.linalg.cholesky(A)
A_prime @ A_prime.T

array([[2., 1.],
       [1., 2.]])