In [1]:
import scipy as sp
import numpy as np

## LU 分解

$$
A = P @ L @ U
$$

- P is a permutation matrix
- L lower triangular with **unit diagonal elements**,
- U upper triangular.

In [2]:
A = np.array([[2, 5, 8, 7], 
              [5, 2, 2, 8], 
              [7, 5, 6, 6], 
              [5, 4, 4, 8]])
A

array([[2, 5, 8, 7],
       [5, 2, 2, 8],
       [7, 5, 6, 6],
       [5, 4, 4, 8]])

In [17]:
P, L, U = sp.linalg.lu(A)

In [7]:
np.allclose(A, P @ L @ U)

True

In [19]:
# 要看每一行为1的entry所在的 column index
# 1, 3, 0, 2
P

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
# L

In [12]:
# U

In [14]:
P, L, U = sp.linalg.lu(A, p_indices=True)

In [15]:
P

array([1, 3, 0, 2], dtype=int32)

In [16]:
np.allclose(A, L[P, :] @ U)

True

## Cholesky 分解

- 一个矩阵能够被 Cholesky 分解的前提就是必须是正定的（这也是 check 一个矩阵是否为正定矩阵的方法）
    - 首先需要是对称的方阵
- Cholesky 分解被用于快速求解如下的线性方程组

$$
Ax=b
$$

- A = L @ L.T
- A = U.T @ U

In [20]:
A = np.array([[6, 3, 4, 8], 
              [3, 6, 5, 1], 
              [4, 5, 10, 7], 
              [8, 1, 7, 25]])
A

array([[ 6,  3,  4,  8],
       [ 3,  6,  5,  1],
       [ 4,  5, 10,  7],
       [ 8,  1,  7, 25]])

In [22]:
L = np.linalg.cholesky(A)

In [23]:
L

array([[ 2.44948974,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  2.12132034,  0.        ,  0.        ],
       [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
       [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]])

In [24]:
np.allclose(L @ L.T, A)

True

In [30]:
L = np.linalg.cholesky(A)

In [31]:
U = L.T
np.allclose(U.T @ U, A)

True

### QR 分解

$$
A_{m\times n}=Q_{m\times n}R_{n\times n}
$$
- A 不要求一定是方阵，$A\in\mathbb R^{m\times n}, m\geq n$
    - $Q$ 列正交；
    - $R$ 为上三角的方阵；
- 最小二乘
    - $Ax=b$
    - $QRx=b$
    - $Rx=Q^Tb$

In [13]:
A = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 11.],
              [10., 12., 13.]])

In [14]:
Q, R = np.linalg.qr(A)

In [15]:
R

array([[-12.88409873, -15.36778041, -18.1619223 ],
       [  0.        ,   0.91177042,   0.97784074],
       [  0.        ,   0.        ,  -2.0465595 ]])

In [6]:
Q

array([[-0.07761505,  0.88534229, -0.35407604],
       [-0.31046021,  0.25106722, -0.05665217],
       [-0.54330537, -0.38320786, -0.73647816],
       [-0.77615053,  0.07928438,  0.57360318]])

In [7]:
Q.T @ Q

array([[ 1.00000000e+00, -4.46366570e-16,  2.46478751e-16],
       [-4.46366570e-16,  1.00000000e+00, -2.10349284e-16],
       [ 2.46478751e-16, -2.10349284e-16,  1.00000000e+00]])

In [8]:
b = np.array([6., 15., 26., 35.])

In [9]:
QT_b = Q.T @ b

In [11]:
x = np.linalg.solve(R, QT_b)
x

array([1., 1., 1.])

In [12]:
np.linalg.lstsq(A, b, rcond=None)

(array([1., 1., 1.]),
 array([9.96557415e-31]),
 np.int32(3),
 array([27.11639294,  1.53931299,  0.5759769 ]))