## basics

$$
M=PDP^{-1}
$$


- 对角化的形式不止一种；
- $P$ 可以是特征向量构成的矩阵；（$MP=PD$）

## sympy

In [10]:
from sympy import * 

In [11]:
M = Matrix([[3, -2, 4, -2], 
            [5, 3, -3, -2],
            [5, -2, 2, -2],
            [5, -2, -3, 3]])

In [6]:
P, D = M.diagonalize()

In [7]:
P

Matrix([
[0, 1, 1,  0],
[1, 1, 1, -1],
[1, 1, 1,  0],
[1, 1, 0,  1]])

In [8]:
D

Matrix([
[-2, 0, 0, 0],
[ 0, 3, 0, 0],
[ 0, 0, 5, 0],
[ 0, 0, 0, 5]])

In [12]:
import numpy as np

In [16]:
P = np.array(P).astype(np.float64)
D = np.array(D).astype(np.float64)
P.dot(D).dot(np.linalg.inv(P))

array([[ 3., -2.,  4., -2.],
       [ 5.,  3., -3., -2.],
       [ 5., -2.,  2., -2.],
       [ 5., -2., -3.,  3.]])

## numpy

In [19]:
from scipy.linalg import eig

def diagonalize_matrix(matrix):
    # 计算特征值和特征向量
    eigenvalues, eigenvectors = eig(matrix)

    # 检查特征向量是否形成了基，即是否线性无关
    if np.linalg.matrix_rank(eigenvectors) != matrix.shape[0]:
        return None, None

    # 对角矩阵，其对角线元素是特征值
    D = np.diag(eigenvalues)

    # 特征向量矩阵 P
    P = eigenvectors

    return P, D

In [20]:
M = np.array(M).astype(np.float64)
P, D = diagonalize_matrix(M)

In [21]:
P

array([[ 5.00000000e-01,  0.00000000e+00, -5.77350269e-01,
        -6.07237672e-01],
       [ 5.00000000e-01, -5.77350269e-01, -6.17589503e-16,
        -5.01300427e-01],
       [ 5.00000000e-01, -5.77350269e-01, -5.77350269e-01,
        -6.07237672e-01],
       [ 5.00000000e-01, -5.77350269e-01, -5.77350269e-01,
        -1.05937245e-01]])

In [22]:
D

array([[ 3.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -2.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  5.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  5.+0.j]])

In [23]:
P.dot(D).dot(np.linalg.inv(P))

array([[ 3.+0.j, -2.+0.j,  4.+0.j, -2.+0.j],
       [ 5.+0.j,  3.+0.j, -3.+0.j, -2.+0.j],
       [ 5.+0.j, -2.+0.j,  2.+0.j, -2.+0.j],
       [ 5.+0.j, -2.+0.j, -3.+0.j,  3.+0.j]])