## 对角化与特征值分解

- 对 $A$ 进行特征值分解
    - $Q=\left[\mathbf v_1, \mathbf v_2, \cdots, \mathbf v_n\right]$
    - $AQ=\left[\lambda_1\mathbf v_1, \lambda_2\mathbf v_2, \cdots, \lambda_n\mathbf v_n\right]$
    - $AQ=Q\Lambda$
        - $Ax=\sum_ix_ia_i$

        $$
        \Lambda=\begin{pmatrix}
        \lambda_1 & 0 & \cdots & 0 \\
        0 & \lambda_2 & \cdots & 0 \\
        \vdots & \vdots & \ddots & \vdots \\
        0 & 0 & \cdots & \lambda_n
        \end{pmatrix} 
        $$
    - $A=Q\Lambda Q^{-1}$

    

### 实对称矩阵

- 当 $A$ 是实对称矩阵时，$A=Q\Lambda Q^T$
    - $(\lambda_i, v_i), (\lambda_j, v_j)$
    - $v_i^TAv_j=\lambda_jv_i^Tv_j$
    - $v_j^TAv_i=\lambda_iv_j^Tv_i$
    - 因为 $A=A^T$，所以有 $v_i^TAv_j=v_j^TAv_i$（两等式左侧），因此有 $\lambda_jv_i^Tv_j=\lambda_iv_j^Tv_i$（等式右侧）
        - 因为 $\lambda_i \neq \lambda_j$，所以只能是 $v_i\perp v_j$
    - 所以 $Q$ 是一个正交阵（orthogonal matrix）
        - $Q^TQ=I, \quad v_i^Tv_i=1, v_i^Tv_j=0$

In [3]:
import numpy as np
from numpy.linalg import eigh

In [16]:
a = np.asarray([[ 2.,  1.,  0.,  0.], 
                [ 1.,  2.,  0.,  0.], 
                [ 0.,  0.,  2.,  1.], 
                [ 0.,  0.,  1.,  2.]])

In [17]:
Lambda, Q = eigh(a)

In [18]:
Q.T

array([[-0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678,  0.        ,  0.        ]])

In [19]:
np.linalg.inv(Q)

array([[-0.70710678,  0.70710678, -0.        , -0.        ],
       [-0.        , -0.        , -0.70710678,  0.70710678],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678,  0.        ,  0.        ]])

In [23]:
np.diag(Lambda)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [24]:
Q.dot(np.diag(Lambda)).dot(Q.T)

array([[2., 1., 0., 0.],
       [1., 2., 0., 0.],
       [0., 0., 2., 1.],
       [0., 0., 1., 2.]])

In [26]:
Q.dot(np.diag(Lambda)).dot(np.linalg.inv(Q))

array([[2., 1., 0., 0.],
       [1., 2., 0., 0.],
       [0., 0., 2., 1.],
       [0., 0., 1., 2.]])